Repository benediktscheffel/nodocs, pull requests merged in 2024-07, with the labels that each got.

#42 Feature/11 implement search feature on home page
  android/app/src/main/AndroidManifest.xml
  assets/translations/de.json
  assets/translations/en.json
  lib/features/filesystem/pages/home_page.dart
  lib/features/filesystem/services/file_system_access/file_system_service.dart
  lib/features/filesystem/services/file_system_access/implementation/file_system_service_impl.dart
  lib/features/scan/widgets/scan_title_input.dart
  lib/features/search/controller/implementation/search_result_controller_impl.dart
  lib/features/search/controller/implementation/search_result_controller_impl.g.dart
  lib/features/search/controller/implementation/search_result_providers.dart
  lib/features/search/controller/implementation/search_result_providers.g.dart
  lib/features/search/controller/search_result_controller.dart
  lib/features/search/model/search_result_model.dart
  lib/features/search/model/search_result_model.freezed.dart
  lib/features/search/widgets/search_bar.dart
  lib/features/search/widgets/search_result_tile.dart
  lib/gen/locale_keys.g.dart
  lib/widgets/search_bar.dart
Labels: enhancement

#49 Docs/40 write documentation bene
  README.md
  lib/features/tags/widgets/tag_chip_container.dart
Labels: documentation

#50 Fix/43 prevent the camera from rotating
  lib/features/scan/pages/save_page.dart
  lib/features/scan/pages/scan_page.dart
  lib/features/scan/widgets/scan_camera.dart
  lib/features/scan/widgets/scan_camera_footer.dart
  lib/features/search/widgets/search_bar.dart
  lib/widgets/title_with_button.dart
  pubspec.yaml
Labels: bug
